### PR TITLE
Retro Games using pixel based canvas

### PR DESCRIPTION
**Pull request by y0014984**
## Misc
- [x] Sync module to computer to allow games

## Functions
- [x] createCanvas
- [x] setPixelColor
- [x] getPixelColor
- [x] getCanvasWidth
- [x] getCanvasHeight
- [x] showSplashScreen

## Games
- [x] snake

### CODE REVIEW

**Comment by y0014984** [comment]
@GermanHydrogen You already can have a look at this pull request, if you are interested. The core seems to be useable and `snake` is fun. From now on I will only add useful 'game engine' commands and additional games.

**Comment by GermanHydrogen** [comment]
> @GermanHydrogen You already can have a look at this pull request, if you are interested. The core seems to be useable and `snake` is fun. From now on I will only add useful 'game engine' commands and additional games.

I think the games should not be on the OS per default. We could use a module to let the mission builder install them.

**Comment by y0014984** [comment]
> I think the games should not be on the OS per default. We could use a module to let the mission builder install them.

I knew that you would say that. Therefaore I already added a Module. Only if the Module is synced to the computer, the games will show up.

**Comment by y0014984** [comment]
It's to much to create all games now. So please review as it is. Additional games and function will get into that later.

**Comment by y0014984** [comment]
Last things to do:
[ ] inherit commands from osCommand instead of introducing new classes

**Comment by y0014984** [comment]
This Pull Request will be discontinued and the branch will be deleted due to mistakes with branch rebase. The new branch and Pull Request can be found here #317

**Pull request closed without merging**
